In [56]:
import pandas as pd

In [57]:
pd.__version__

'2.3.3'

In [58]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2026-01-12 11:17:12--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv.3’

car_fuel_efficiency 100%[===================>] 853.70K  --.-KB/s    in 0.01s

2026-01-12 11:17:12 (82.0 MB/s) - ‘car_fuel_efficiency.csv.3’ saved [874188/874188]

In [59]:
data = pd.read_csv('car_fuel_efficiency.csv')

In [60]:
data.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [61]:
data['num_cylinders']

0       3.0
1       5.0
2       NaN
3       4.0
4       1.0
       ...
9699    5.0
9700    NaN
9701    2.0
9702    4.0
9703    3.0
Name: num_cylinders, Length: 9704, dtype: float64

In [62]:
data[['engine_displacement', 'horsepower', 'origin']]

      engine_displacement  horsepower  origin
0                     170       159.0  Europe
1                     130        97.0     USA
2                     170        78.0  Europe
3                     220         NaN     USA
4                     210       140.0  Europe
...                   ...         ...     ...
9699                  140       164.0  Europe
9700                  180       154.0     USA
9701                  220       138.0     USA
9702                  230       177.0     USA
9703                  270       140.0    Asia

[9704 rows x 3 columns]

In [63]:
data.describe()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,num_doors,fuel_efficiency_mpg
count,9704.000000,9222.000000,8996.000000,9704.000000,8774.000000,9704.000000,9202.000000,9704.000000
mean,199.708368,3.962481,149.657292,3001.280993,15.021928,2011.484027,-0.006412,14.985243
std,49.455319,1.999323,29.879555,497.894860,2.510339,6.659808,1.048162,2.556468
min,10.000000,0.000000,37.000000,952.681761,6.000000,2000.000000,-4.000000,6.200971
25%,170.000000,3.000000,130.000000,2666.248985,13.300000,2006.000000,-1.000000,13.267459
50%,200.000000,4.000000,149.000000,2993.226296,15.000000,2012.000000,0.000000,15.006037
75%,230.000000,5.000000,170.000000,3334.957039,16.700000,2017.000000,1.000000,16.707965
max,380.000000,13.000000,271.000000,4739.077089,24.300000,2023.000000,4.000000,25.967222

In [64]:
data['fuel_type'].nunique()

2

In [65]:
data.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [66]:
data['origin'].unique()

array(['Europe', 'USA', 'Asia'], dtype=object)

In [67]:
data[data['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(23.759122836520497)

In [68]:
med_before = data['horsepower'].median()
print(med_before)
mod = data['horsepower'].mode()[0]
print(mod)
data['horsepower'] = data['horsepower'].fillna(mod)
med_after = data['horsepower'].median()
print(med_after)

149.0
152.0
152.0

In [79]:
X = data[data['origin'] == 'Asia'][['vehicle_weight', 'model_year']].iloc[:7].to_numpy()

In [86]:
XTX = np.dot(X.T, X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [82]:
XTX_inv = np.linalg.inv(XTX)

In [83]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [84]:
w = XTX_inv @ X.T @ y

In [85]:
w.sum()

np.float64(0.5187709081074016)