# 3. Machine Learning for Classification

Logistic regression to predict churn

## 3.1 Churn Prediction project 
- Dataset: https://www.kaggle.com/blastchar/telco-customer-churn

## 3.2 Data Preparation

- Download the data, read it with pandas
- Look at the data
- Make column names and values look uniform
- Check if all the columns read correctly
- Check if the churn variable needs any preparation

In [5]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [6]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

In [7]:
!wget $data -O data-week-3.csv

--2026-01-16 19:38:31--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 977501 (955K) [text/plain]
Saving to: ‘data-week-3.csv’

data-week-3.csv     100%[===================>] 954.59K  --.-KB/s    in 0.009s

2026-01-16 19:38:32 (103 MB/s) - ‘data-week-3.csv’ saved [977501/977501]

In [8]:
df = pd.read_csv('data-week-3.csv')
df.head()

   customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [9]:
df.shape

(7043, 21)

As we cannot see all the columns contents which are replaced by ... we can do so by taking transpose of head of matrix

In [10]:
df.head().T

                                 0  ...                 4
customerID              7590-VHVEG  ...        9237-HQITU
gender                      Female  ...            Female
SeniorCitizen                    0  ...                 0
Partner                        Yes  ...                No
Dependents                      No  ...                No
tenure                           1  ...                 2
PhoneService                    No  ...               Yes
MultipleLines     No phone service  ...                No
InternetService                DSL  ...       Fiber optic
OnlineSecurity                  No  ...                No
OnlineBackup                   Yes  ...                No
DeviceProtection                No  ...                No
TechSupport                     No  ...                No
StreamingTV                     No  ...                No
StreamingMovies                 No  ...                No
Contract            Month-to-month  ...    Month-to-month
PaperlessBilling               Yes  ...               Yes
PaymentMethod     Electronic check  ...  Electronic check
MonthlyCharges               29.85  ...              70.7
TotalCharges                 29.85  ...            151.65
Churn                           No  ...               Yes

[21 rows x 5 columns]

In [11]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)

for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')

In [12]:
df.head().T

                                 0  ...                 4
customerid              7590-vhveg  ...        9237-hqitu
gender                      female  ...            female
seniorcitizen                    0  ...                 0
partner                        yes  ...                no
dependents                      no  ...                no
tenure                           1  ...                 2
phoneservice                    no  ...               yes
multiplelines     no_phone_service  ...                no
internetservice                dsl  ...       fiber_optic
onlinesecurity                  no  ...                no
onlinebackup                   yes  ...                no
deviceprotection                no  ...                no
techsupport                     no  ...                no
streamingtv                     no  ...                no
streamingmovies                 no  ...                no
contract            month-to-month  ...    month-to-month
paperlessbilling               yes  ...               yes
paymentmethod     electronic_check  ...  electronic_check
monthlycharges               29.85  ...              70.7
totalcharges                 29.85  ...            151.65
churn                           no  ...               yes

[21 rows x 5 columns]

In [13]:
df.dtypes

customerid           object
gender               object
seniorcitizen         int64
partner              object
dependents           object
tenure                int64
phoneservice         object
multiplelines        object
internetservice      object
onlinesecurity       object
onlinebackup         object
deviceprotection     object
techsupport          object
streamingtv          object
streamingmovies      object
contract             object
paperlessbilling     object
paymentmethod        object
monthlycharges      float64
totalcharges         object
churn                object
dtype: object

In [14]:
pd.to_numeric(df['totalcharges'])

ValueError: Unable to parse string "_" at position 488

The above error indicates that total_charges does not only contain numbers to be parsed to numeric but also string "_" because in the previous cell we replaced " " with _

In [15]:
tc = pd.to_numeric(df['totalcharges'], errors='coerce')

In [16]:
df['totalcharges'] = pd.to_numeric(df['totalcharges'], errors='coerce')

In [17]:
df['totalcharges'] = df['totalcharges'].fillna(0)

In [18]:
df[tc.isnull()][['customerid', 'totalcharges']]

      customerid  totalcharges
488   4472-lvygi           0.0
753   3115-czmzd           0.0
936   5709-lvoeq           0.0
1082  4367-nuyao           0.0
1340  1371-dwpaz           0.0
3331  7644-omvmy           0.0
3826  3213-vvolg           0.0
4380  2520-sgtta           0.0
5218  2923-arzlg           0.0
6670  4075-wkniu           0.0
6754  2775-sefee           0.0

In [19]:
df['churn'] = (df['churn'] == 'yes').astype(int)

In [20]:
df.T

                              0     ...                       7042
customerid              7590-vhveg  ...                 3186-ajiek
gender                      female  ...                       male
seniorcitizen                    0  ...                          0
partner                        yes  ...                         no
dependents                      no  ...                         no
tenure                           1  ...                         66
phoneservice                    no  ...                        yes
multiplelines     no_phone_service  ...                         no
internetservice                dsl  ...                fiber_optic
onlinesecurity                  no  ...                        yes
onlinebackup                   yes  ...                         no
deviceprotection                no  ...                        yes
techsupport                     no  ...                        yes
streamingtv                     no  ...                        yes
streamingmovies                 no  ...                        yes
contract            month-to-month  ...                   two_year
paperlessbilling               yes  ...                        yes
paymentmethod     electronic_check  ...  bank_transfer_(automatic)
monthlycharges               29.85  ...                     105.65
totalcharges                 29.85  ...                     6844.5
churn                            0  ...                          0

[21 rows x 7043 columns]

## 3.3 Setting up Validation Framework

- Perform train/test/validation split using Sklearn package

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
#to get documentation of package
train_test_split?

Signature:
train_test_split(
    *arrays,
    test_size=None,
    train_size=None,
    random_state=None,
    shuffle=True,
    stratify=None,
)
Docstring:
Split arrays or matrices into random train and test subsets.

Quick utility that wraps input validation,
``next(ShuffleSplit().split(X, y))``, and application to input data
into a single call for splitting (and optionally subsampling) data into a
one-liner.

Read more in the :ref:`User Guide <cross_validation>`.

Parameters
----------
*arrays : sequence of indexables with same length / shape[0]
    Allowed inputs are lists, numpy arrays, scipy-sparse
    matrices or pandas dataframes.

test_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the proportion
    of the dataset to include in the test split. If int, represents the
    absolute number of test samples. If None, the value is set to the
    complement of the train size. If ``train_size`` is also None, it will
    be set to 0.25.

train_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the
    proportion of the dataset to include in the train split. If
    int, represents the absolute number of train samples. If None,
    the value is automatically set to the complement of the test size.

random_state : int, RandomState instance or None, default=None
    Controls the shuffling applied to the data before applying the split.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.

shuffle : bool, default=True
    Whether or not to shuffle the data before splitting. If shuffle=False
    then stratify must be None.

stratify : array-like, default=None
    If not None, data is split in a stratified fashion, using this as
    the class labels.
    Read more in the :ref:`User Guide <stratification>`.

Returns
-------
splitting : list, length=2 * len(arrays)
    List containing train-test split of inputs.

    .. versionadded:: 0.16
        If the input is sparse, the output will be a
        ``scipy.sparse.csr_matrix``. Else, output type is the same as the
        input type.

Examples
--------
>>> import numpy as np
>>> from sklearn.model_selection import train_test_split
>>> X, y = np.arange(10).reshape((5, 2)), range(5)
>>> X
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
>>> list(y)
[0, 1, 2, 3, 4]

>>> X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)
...
>>> X_train
array([[4, 5],
       [0, 1],
       [6, 7]])
>>> y_train
[2, 0, 3]
>>> X_test
array([[2, 3],
       [8, 9]])
>>> y_test
[1, 4]

>>> train_test_split(y, shuffle=False)
[[0, 1, 2], [3, 4]]

>>> from sklearn import datasets
>>> iris = datasets.load_iris(as_frame=True)
>>> X, y = iris['data'], iris['target']
>>> X.head()
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
>>> y.head()
0    0
1    0
2    0
3    0
4    0
...

>>> X_train, X_test, y_train, y_test = train_test_split(
... X, y, test_size=0.33, random_state=42)
...
>>> X_train.head()
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
96                 5.7               2.9                4.2               1.3
105                7.6               3.0                6.6               2.1
66                 5.6               3.0                4.5               1.5
0                  5.1               3.5                1.4               0.2
122                7.7               2.8                6.7               2.0
>>> y_train.head()
96     1
105    2
66     1
0      0
122    2
...
>>> X_test.head()
    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
73                 6.1               2.8                4.7               1.2
18                 5.7               3.8                1.7               0.3
118                7.7               2.6                6.9               2.3
78                 6.0               2.9                4.5               1.5
76                 6.8               2.8                4.8               1.4
>>> y_test.head()
73     1
18     0
118    2
78     1
76     1
...
File:      /usr/local/python/3.12.1/lib/python3.12/site-packages/sklearn/model_selection/_split.py
Type:      function

In [25]:
df_fulltrain, df_test = train_test_split(df, test_size=0.2, random_state=1)

In [26]:
df_train, df_val = train_test_split(df_fulltrain, test_size=0.25, random_state=1)

In [29]:
len(df_fulltrain), len(df_train), len(df_val), len(df_test)

(5634, 4225, 1409, 1409)

In [32]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [33]:
y_train = df_train['churn'].values
y_val = df_val['churn'].values
y_test = df_test['churn'].values

In [34]:
del df_train['churn']
del df_val['churn']
del df_test['churn']

## 3.4 EDA

- check missing values
- look at target vriable (churn)
- look at numerical and categorical variables

In [35]:
df_fulltrain = df_fulltrain.reset_index(drop=True)

In [36]:
df_fulltrain.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [37]:
df_fulltrain['churn'].value_counts()

churn
0    4113
1    1521
Name: count, dtype: int64

In [38]:
# to see percentage

df_fulltrain['churn'].value_counts(normalize=True)

churn
0    0.730032
1    0.269968
Name: proportion, dtype: float64

27% is our global churn rate which is same as mean of churn column

In [41]:
global_churn_rate = df_fulltrain['churn'].mean()
round(global_churn_rate, 2)

np.float64(0.27)

In [42]:
df_fulltrain.dtypes

customerid           object
gender               object
seniorcitizen         int64
partner              object
dependents           object
tenure                int64
phoneservice         object
multiplelines        object
internetservice      object
onlinesecurity       object
onlinebackup         object
deviceprotection     object
techsupport          object
streamingtv          object
streamingmovies      object
contract             object
paperlessbilling     object
paymentmethod        object
monthlycharges      float64
totalcharges        float64
churn                 int64
dtype: object

In [43]:
numerical = ['tenure', 'monthlycharges', 'totalcharges']

In [44]:
df_fulltrain.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='object')

In [45]:
categorical = ['gender', 'seniorcitizen', 'partner', 'dependents',
       'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod']

In [51]:
df_fulltrain[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64